### ISSUE TITLE
Amazon Subscription Module Issue

### ISSUE THREAD

**Issue by alpine-adriana** [CPIGroup/phpAmazonMWS#160] opened 2018-07-21 18:36 UTC
Now your subscription module has some issues.
I think Subscription response XML parsing part has issues.

**Comment by Peardian** [comment] 2018-07-23 14:12
Could you provide more information about what the problem is?

**Comment by Peardian** [comment] 2019-05-01 14:18
It has been over nine months without a reply, so I'm going to close this.

**Closed by Peardian** 2019-05-01 14:18 UTC
