### ISSUE TITLE
Unable to Download MWS Report more than 2mb

### ISSUE THREAD

**Issue by walkout** [CPIGroup/phpAmazonMWS#66] opened 2016-03-03 10:39 UTC
Hi ,
So After spending 3-4 days of checking , I still can't figure out why i am not able to download report more than 2mb.

This is what i have made modifications to the code , Would appreciate if you could point me in the right direction or why this is happening.

My curl request modified - i was trying various options but they dont seem to work.

```php
function fetchURL ($url, $param) {
		   
		set_time_limit(0);
        $return = array();
		
		//$fp1 = fopen('request.txt','w+');
		//require_once 'MyStream.php';
		//stream_wrapper_register("test", "MyStream") or die("Failed to register protocol");
		//$fp = fopen("test://MyTestVariableInMemory", "r+");
		$filepath = 'request2.txt';
        $ch = curl_init();     
		curl_setopt($ch,CURLOPT_URL,$url);	
		//curl_setopt($ch, CURLOPT_RANGE, 2000-5000);
	
		curl_setopt($ch,CURLOPT_HEADER, false);	
		curl_setopt($ch, CURLOPT_HEADERFUNCTION, array($this,'read_header' ));
		//curl_setopt($ch, CURLOPT_BUFFERSIZE, 256);
        curl_setopt($ch,CURLOPT_RETURNTRANSFER, true);		
        curl_setopt($ch,CURLOPT_TIMEOUT, 0);
        //curl_setopt($ch,CURLOPT_FORBID_REUSE, 0);
       // curl_setopt($ch,CURLOPT_FRESH_CONNECT, 0);  
		//curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
		
        if (!empty($param)){
            if (!empty($param['Header'])){
                curl_setopt($ch,CURLOPT_HTTPHEADER, $param['Header']);
            }
            if (!empty($param['Post'])){
                curl_setopt($ch,CURLOPT_POSTFIELDS, $param['Post']);
            }
        }
		//curl_setopt($ch, CURLOPT_PROGRESSFUNCTION, array($this,'progresscurl'));
		curl_setopt($ch, CURLOPT_WRITEFUNCTION, array($this,'writecurl'));	
		//curl_setopt($ch, CURLOPT_FILE, $fp); 
		//curl_setopt($ch, CURLOPT_VERBOSE, true);
		//curl_setopt($ch, CURLOPT_STDERR, $fp1);
			
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        $data = curl_exec($ch);
		//echo $data;
		$info = curl_getinfo($ch);
		var_dump($data);
		var_dump($info);		
		
        if ( curl_errno($ch) ) {
                $return['ok'] = -1;
                $return['error'] = curl_error($ch);
                return $return;
        }
        
        if (is_numeric(strpos($data, 'HTTP/1.1 100 Continue'))) {
            $data=str_replace('HTTP/1.1 100 Continue', '', $data);
        }
        $data = preg_split("/\r\n\r\n/",$data, 2, PREG_SPLIT_NO_EMPTY);
        if (!empty($data)) {
                $return['head'] = ( isset($data[0]) ? $data[0] : null );
                $return['body'] = ( isset($data[1]) ? $data[1] : null );
        } else {
                $return['head'] = null;
                $return['body'] = null;
        }
        
        $matches = array();
        $data = preg_match("/HTTP\/[0-9.]+ ([0-9]+) (.+)\r\n/",$return['head'], $matches);
        if (!empty($matches)) {
                $return['code'] = $matches[1];
                $return['answer'] = $matches[2];
        }
        
        $data = preg_match("/meta http-equiv=.refresh. +content=.[0-9]*;url=([^'\"]*)/i",$return['body'], $matches);
        if (!empty($matches)) {
                $return['location'] = $matches[1];
                $return['code'] = '301';
        }
        
        if ( $return['code'] == '200' || $return['code'] == '302' ) {
                $return['ok'] = 1;
        } else {
                $return['error'] = (($return['answer'] and $return['answer'] != 'OK') ? $return['answer'] : 'Something wrong!');
                $return['ok'] = 0;
        }
        
        foreach (preg_split('/\n/', $return['head'], -1, PREG_SPLIT_NO_EMPTY) as $value) {
                $data = preg_split('/:/', $value, 2, PREG_SPLIT_NO_EMPTY);
                if (is_array($data) and isset($data['1'])) {
                        $return['headarray'][$data['0']] = trim($data['1']);
                }
        }
        
        curl_close($ch);
		//fclose($fp);
		
        
        return $return;
       }
```

```php
	public function processLine($line){
		
		file_put_contents('request2.txt', $line, FILE_APPEND);
		
		
	}
	
	public function writecurl($ch,$data){
		
		//fclose($fp);
		
		$this->currentLine .= $data;
        $lines = explode("\n", $this->currentLine);
        // The last line could be unfinished. We should not
        // proccess it yet.
        $numLines = count($lines) - 1;
        $this->currentLine = $lines[$numLines]; // Save for the next callback.

        for ($i = 0; $i < $numLines; ++$i) {
            $this->processLine($lines[$i]); // Do whatever you want
            ++$this->totalLineCount; // Statistics.
            $this->totalLength += strlen($lines[$i]) + 1;
        }
		
		
        return strlen($data); // Ask curl for more data (!= value will stop).
		
		
		//$len = strlen($data);
		
		//return $len;			
		//return null;
	}
```

**Comment by Peardian** [comment] 2016-03-10 23:08
I have not had a chance to look into this yet, but this sounds like it could potentially be a problem with your settings. Can you first verify that you are able to download 3+ MB files through curl from a source other than Amazon?

**Comment by Approach** [comment] 2016-03-11 02:32
Hello, parroting what Peardian is saying, it is very likely this problem is in your php.ini or system settings

Even though you are working with downloads, you want to check these settings in php.ini:
memory_limit = 48M
upload_max_filesize = 32M
post_max_size = 32M

You probably also want to look for any other file/memory limitations. For example check output_buffering settings. You might just run a phpinfo() command and look through for anything related to curl or limits.

If all else continues to fail you can download to a temporary file..
exec("wget $serviceURL $tmpFilepath 2>&1 &", $output);

**Comment by walkout** [comment] 2016-03-12 04:14
Hi Peradian and Approach ,

Those were the first thing that i set.

I am able to download files more than 3 mb on my server.

I reset them earlier - considering it may be a server issue. i have rechecked values from phpinfo.

`memory_limit = 1024M
upload_max_filesize = 300M
post_max_size = 300M
output bufferng is also very large.
`


I am placing my responce header below so you could check 

`Header: HTTP/1.1 200 OK 
Header: Server: Server 
Header: Date: Sat, 12 Mar 2016 03:18:54 GMT 
Header: Content-Type: text/plain;charset=UTF-8 
Header: Content-Length: 2121720 
Header: Connection: keep-alive 
Header: x-mws-quota-max: 60.0 
Header: x-mws-quota-remaining: 58.0 
Header: x-mws-quota-resetsOn: 2016-03-12T03:59:00.000Z 
Header: Content-MD5: gy5W0Qk2A18XtEc38rO0zQ== 
Header: x-mws-response-context: gA8ONKa5zZwmXyyR2LDdP/Ftc+z0dcererqrWz2YqQxLiSSwDtquzZocbp6NVW0UejYPeeIOxoof AZsZH+Co3LB3kjkgkPO1l 
Header: x-mws-response-context: /smQov1Tq9BlCEFtdkuyRWrqKX6jxttnnUihCaQSfbIdQvKRSLY+15PkD7878u8QdxHPo4au3QQ65RNq /+PYBmHBGw== 
Header: x-amz-request-id: b82bdd43-6985-4af8-9b62-c35faa0de020 
Header: x-mws-request-id: b82b3d43-6985-4af8-9b62-c35faa0de020 
Header: x-mws-timestamp: 2016-03-12T03:18:54.194Z 
Header: Vary: Accept-Encoding,User-Agent 
Header: `


`array (size=26)
  'url' => string 'https://mws.amazonservices.in/' (length=30)
  'content_type' => string 'text/plain;charset=UTF-8' (length=24)
  'http_code' => int 200
  'header_size' => int 727
  'request_size' => int 459
  'filetime' => int -1
  'ssl_verify_result' => int 20
  'redirect_count' => int 0
  'total_time' => float 13.5
  'namelookup_time' => float 0
  'connect_time' => float 0.343
  'pretransfer_time' => float 1.047
  'size_upload' => float 328
  'size_download' => float 2121720
  'speed_download' => float 157164
  'speed_upload' => float 24
  'download_content_length' => float 2121720
  'upload_content_length' => float 328
  'starttransfer_time' => float 1.593
  'redirect_time' => float 0
  'redirect_url' => string '' (length=0)
  'primary_ip' => string '51.239.30.192' (length=13)
  'certinfo' => 
    array (size=0)
      empty
  'primary_port' => int 443
  'local_ip' => string '192.168.1.33' (length=12)
  'local_port' => int 56382`


Also there is one more thing that i am not sure of - 

While checking headers using live http headers - 

I do see a time-out of 5sec from Amazon server.


Not sure , if using exec in the code would be a good idea for me.

**Comment by Peardian** [comment] 2016-05-16 22:19
If temp stream is being used, that is could be the cause. Once the temp stream reaches its max size, it is supposed to create a temp file, so it could be having trouble creating that file. Alternatively, the default max size of the temp stream can be changed with a URL parameter when opening the stream.

Unless this does not solve the problem, I will probably close this soon.

**Comment by walkout** [comment] 2016-06-06 14:21
Hi ,I tried the application , But it is still not downloading the full file.
Can you look into it as paid support?
Ritesh

Date: Thu, 26 May 2016 06:53:39 -0700

**Comment by Peardian** [comment] 2016-06-06 15:26
I can try downloading some reports later this week or next week. If I don't have any problems with it, though, then it is likely a problem with your settings.

**Comment by Peardian** [comment] 2016-06-08 20:37
I was able to download a 60 MB report from Amazon just fine. The problem is either with your PHP settings or your connection settings.

**Closed by Peardian** 2016-06-08 20:37 UTC
